name: NPM Package Publish

on:
  push:
    branches:
      - main
      - next
      - beta
      - alpha
      - '[0-9]+.x' # maintenance releases

concurrency:
  group: publish-${{ github.ref }}

env:
  NODE_VERSION: 22.x
  HUSKY: 0

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Configure package manager
        run: |
          npm config set '//registry.npmjs.org/:_authToken' ${{ secrets.NPM_TOKEN }}

      - name: Install Dependencies
        run: npm ci

      - name: Run Build
        run: npm run build

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: ^18
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'main',
              'next',
              {name: 'beta', prerelease: true},
              {name: 'alpha', prerelease: true}
            ]
